# EZPlugV2 Collector Configuration

[mqtt]
broker_ip = "192.168.1.195"
broker_port = 1883
topic_base = "EZPlugV2_743EEC"
client_id = "ezplugv2_sqlite_logger_dev"

# Telemetry period in seconds (10..3600)
# https://tasmota.github.io/docs/Peripherals/#update-interval
tele_period = 10

[database]
filename = "ezplug.db"

[logging]
# Path to the log configuration file for dynamic log level changes
config_file = "log_config.txt"
