[package]
name = "viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
